### ISSUE TITLE
Cannot get past osgi in install

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline-assembly#110]
I have both java 8 and java 7 installed.... I am an end user just wanting to convert some books so that my phone TTS can read them to me. I get this error ever single time try to build this. 
I am on arch linux if that helps. 

Command used is mvn package -P webui -e

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building DAISY Pipeline 2 :: Assembly 1.9.15
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:enforce (enforce-maven) @ assembly ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.7:copy (copy-felix-launcher) @ assembly ---
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.main:?:jar
[INFO] org.apache.felix:org.apache.felix.main:4.4.1:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/bootstrap
[INFO] 
[INFO] --- maven-dependency-plugin:2.7:copy (copy-felix-bundles) @ assembly ---
[INFO] Configured Artifact: ch.qos.logback:logback-classic:1.0.11:jar
[INFO] Configured Artifact: ch.qos.logback:logback-core:1.0.11:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.gogo.command:0.14.0:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.gogo.runtime:0.12.1:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.gogo.shell:0.10.0:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.configadmin:1.6.0:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.dependencymanager:3.1.0:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.eventadmin:1.3.2:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.fileinstall:3.2.6:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.log:1.0.1:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.metatype:1.0.6:jar
[INFO] Configured Artifact: org.apache.felix:org.apache.felix.scr:1.6.2:jar
[INFO] Configured Artifact: org.osgi:org.osgi.enterprise:4.2.0:jar
[INFO] Configured Artifact: org.slf4j:slf4j-api:?:jar
[INFO] Configured Artifact: org.slf4j:jul-to-slf4j:?:jar
[INFO] Configured Artifact: org.slf4j:jcl-over-slf4j:?:jar
[INFO] ch.qos.logback:logback-classic:1.0.11:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] ch.qos.logback:logback-core:1.0.11:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.gogo.command:0.14.0:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.gogo.runtime:0.12.1:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.gogo.shell:0.10.0:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.configadmin:1.6.0:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.dependencymanager:3.1.0:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.eventadmin:1.3.2:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.fileinstall:3.2.6:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.log:1.0.1:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.metatype:1.0.6:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.apache.felix:org.apache.felix.scr:1.6.2:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.osgi:org.osgi.enterprise:4.2.0:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.slf4j:slf4j-api:1.7.2:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.slf4j:jul-to-slf4j:1.7.2:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] org.slf4j:jcl-over-slf4j:1.7.2:jar already exists in /home/anna/Downloads/pipeline-assembly-1.9.15/target/bundles/felix
[INFO] 
[INFO] --- maven-dependency-plugin:2.7:copy (copy-libs-bundles) @ assembly ---
[INFO] Configured Artifact: javax.xml.crypto:jsr105-api:1.0.1:jar
[INFO] Configured Artifact: javax.xml.parsers:jaxp-api:1.4.5:jar
[INFO] Configured Artifact: org.apache.httpcomponents:httpclient-osgi:4.2.5:jar
[INFO] Configured Artifact: org.apache.httpcomponents:httpcore-osgi:4.2.4:jar
[INFO] Configured Artifact: org.daisy.libs:jing:20120724.0.0:jar
[INFO] Configured Artifact: org.eclipse:org.eclipse.gemini.jpa:1.0.0.RELEASE:jar
[INFO] Configured Artifact: org.eclipse.gemini:org.apache.derby:10.8.2.2:jar
[INFO] Configured Artifact: org.eclipse.gemini:org.eclipse.gemini.dbaccess.derby:1.1.0.RELEASE:jar
[INFO] Configured Artifact: org.eclipse.gemini:org.eclipse.gemini.dbaccess.util:1.1.0.RELEASE:jar
[INFO] Configured Artifact: org.eclipse.persistence:org.eclipse.persistence.asm:2.3.2:jar
[INFO] Configured Artifact: org.eclipse.persistence:org.eclipse.persistence.antlr:2.3.2:jar
[INFO] Configured Artifact: org.eclipse.persistence:org.eclipse.persistence.core:2.3.2:jar
[INFO] Configured Artifact: org.eclipse.persistence:org.eclipse.persistence.jpa:2.3.2:jar
[INFO] Configured Artifact: nu.validator.htmlparser:htmlparser:1.4:jar
[INFO] Configured Artifact: org.daisy.libs:com.xmlcalabash:1.0.23:jar
[INFO] Configured Artifact: org.daisy.libs:logback-osgi-adapter:1.0.0:jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.414 s
[INFO] Finished at: 2016-07-28T21:30:34-07:00
[INFO] Final Memory: 14M/127M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.7:copy (copy-libs-bundles) on project assembly: Unable to find artifact. Failure to find org.daisy.libs:logback-osgi-adapter:jar:1.0.0 in http://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command:
[ERROR] mvn install:install-file -DgroupId=org.daisy.libs -DartifactId=logback-osgi-adapter -Dversion=1.0.0 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there:
[ERROR] mvn deploy:deploy-file -DgroupId=org.daisy.libs -DartifactId=logback-osgi-adapter -Dversion=1.0.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR] org.daisy.libs:logback-osgi-adapter:jar:1.0.0
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] central (http://repo.maven.apache.org/maven2/, releases=true, snapshots=true),
[ERROR] restlet-repo (http://maven.restlet.org, releases=true, snapshots=true),
[ERROR] eclipselink (http://download.eclipse.org/rt/eclipselink/maven.repo, releases=true, snapshots=true),
[ERROR] eclipse-gemini-dbaccess (http://download.eclipse.org/gemini/dbaccess/mvn/, releases=true, snapshots=true),
[ERROR] eclipse-gemini-repo (http://download.eclipse.org/gemini/mvn/, releases=true, snapshots=true),
[ERROR] com.springsource.repository.bundles.external (http://repository.springsource.com/maven/bundles/external, releases=true, snapshots=true),
[ERROR] sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.7:copy (copy-libs-bundles) on project assembly: Unable to find artifact.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to find artifact.
    at org.apache.maven.plugin.dependency.fromConfiguration.AbstractFromConfigurationMojo.getArtifact(AbstractFromConfigurationMojo.java:272)
    at org.apache.maven.plugin.dependency.fromConfiguration.AbstractFromConfigurationMojo.getProcessedArtifactItems(AbstractFromConfigurationMojo.java:179)
    at org.apache.maven.plugin.dependency.fromConfiguration.CopyMojo.doExecute(CopyMojo.java:87)
    at org.apache.maven.plugin.dependency.AbstractDependencyMojo.execute(AbstractDependencyMojo.java:167)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Failure to find org.daisy.libs:logback-osgi-adapter:jar:1.0.0 in http://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

Try downloading the file manually from the project website.

Then, install it using the command: 
    mvn install:install-file -DgroupId=org.daisy.libs -DartifactId=logback-osgi-adapter -Dversion=1.0.0 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
    mvn deploy:deploy-file -DgroupId=org.daisy.libs -DartifactId=logback-osgi-adapter -Dversion=1.0.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]


  org.daisy.libs:logback-osgi-adapter:jar:1.0.0

from the specified remote repositories:
  central (http://repo.maven.apache.org/maven2/, releases=true, snapshots=true),
  restlet-repo (http://maven.restlet.org, releases=true, snapshots=true),
  eclipselink (http://download.eclipse.org/rt/eclipselink/maven.repo, releases=true, snapshots=true),
  eclipse-gemini-dbaccess (http://download.eclipse.org/gemini/dbaccess/mvn/, releases=true, snapshots=true),
  eclipse-gemini-repo (http://download.eclipse.org/gemini/mvn/, releases=true, snapshots=true),
  com.springsource.repository.bundles.external (http://repository.springsource.com/maven/bundles/external, releases=true, snapshots=true),
  sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true)

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:221)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:154)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:555)
    at org.apache.maven.plugin.dependency.fromConfiguration.AbstractFromConfigurationMojo.getArtifact(AbstractFromConfigurationMojo.java:264)
    ... 25 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.daisy.libs:logback-osgi-adapter:jar:1.0.0 in http://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:215)
    ... 28 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.daisy.libs:logback-osgi-adapter:jar:1.0.0 in http://repo.maven.apache.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
    at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
    at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    ... 32 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


```

**Comment by josteinaj** [comment]
Hi @confusedlinuxgirl. Thanks for the report!

I recommend you try the latest release version here: https://github.com/daisy/pipeline-assembly/releases/tag/v1.9

As for the error; the latest development versions of Pipeline 2 are not yet stable. I'm not sure why you get the error you are getting but I suspect there's something wrong with either the versions of the modules that are declared and imported or how the maven repositories are configured.

Also, the build documentation is a bit outdated and the `-P webui` won't do anything anymore. The latest release version (Pipeline 2 v1.9) contains a desktop version of the Web UI (which is what the `-P webui` was for). However, newer versions of the Web UI will not be bundled with the default Pipeline 2 distribution, as it will not be meant for use by end-users on their desktops. Newer versions of Pipeline 2 will instead be bundled with a new desktop GUI which works better when installing on your desktop instead of on a server.

Let us know whether or not you find the latest release version useful. :)

**Comment by rdeltour** [comment]
what's the status on this one? could anyone reproduce the issue?

**Comment by bertfrees** [comment]
I'm not gonna try to reproduce because this is about an old version. I'd say close the issue because it's been a year without response from the author.

**Comment by rdeltour** [comment]
ok, sounds reasonable. The author can reopen if needed.
